### ISSUE TITLE
Python implementation request

### ISSUE THREAD

**Issue by impredicative** [rohitash-chandra/CMTL_dynamictimeseries#1]
Very nice work. Is a reusable Python 3 implementation possible? Python is free and so it's easier for users to use. Numpy and optionally Cython can be leveraged as needed. Thanks.

**Comment by rohitash-chandra** [comment]
Thanks, I dont have time to give Python implementation, but can assist or collaborate if you wish. I have Python implementations in related projects: https://rohitash-chandra.github.io/portfolio/
